SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_OUTS O
JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(DATE_FORMAT(O.DATETIME, '%Y-%m-%d'), DATE_FORMAT(I.DATETIME, '%Y-%m-%d')) + 1 DESC
LIMIT 2;