SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS SALES
FROM BOOK B
JOIN BOOK_SALES S ON (B.BOOK_ID = S.BOOK_ID)
JOIN AUTHOR A ON (B.AUTHOR_ID = A.AUTHOR_ID)
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;